# Semgrep configuration for Gen Image Factory
# By putting the rules here, you ensure your local terminal, pre-commit hook, and GitHub CI all use the exact same logic.

rules:
  - p/owasp-electron
  - p/owasp-top-ten
  - p/javascript
  - p/typescript

paths:
  include:
    - src/
    - electron/
    - scripts/
  exclude:
    - "electron/renderer/**"  # Vite build output, not source code (use ** for recursive)
    - "tests/**"
    - "**/*.test.ts"
    - "**/*.test.js"
    - "**/*.spec.ts"
    - "**/*.spec.js"
    - "**/__tests__/**"
