# Semgrep configuration for Gen Image Factory
# Base rulesets are defined in CI workflow (p/owasp-electron, p/javascript, p/typescript)
# This file contains project-specific overrides and exclusions

rules: []

# Exclude heavy/non-source paths from scanning
exclude:
  - node_modules
  - playwright-report
  - web-bundles
  - dist
  - build
  - .next
  - coverage
  - .git

# Paths to scan (defaults to all if not specified)
paths:
  - src
  - tests
  - scripts
  - electron

# Ruleset version pinning (for reproducibility)
# Note: Base rulesets are pinned via --config flags in CI
# Project-specific rule overrides can be added here if needed

