# Semgrep configuration for Gen Image Factory
# By putting the rules here, you ensure your local terminal, pre-commit hook, and GitHub CI all use the exact same logic.
# Path exclusions are handled via .semgrepignore file
# Note: Semgrep 1.146.0 doesn't support 'paths' section with rules in YAML config, so we use .semgrepignore for exclusions

rules:
  - p/owasp-electron
  - p/owasp-top-ten
  - p/javascript
  # Note: p/typescript removed temporarily - Semgrep 1.146.0 doesn't support it in config files
  # JavaScript ruleset covers TypeScript code, so security coverage is maintained
  # TODO: Re-add p/typescript when Semgrep version supports it in config files
