const js = require('@eslint/js');
const react = require('eslint-plugin-react');
const reactHooks = require('eslint-plugin-react-hooks');

module.exports = [
  js.configs.recommended,
  {
    files: ['**/*.{js,jsx}'],
    languageOptions: {
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        window: 'readonly',
        document: 'readonly',
        localStorage: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        queueMicrotask: 'readonly',
        AbortController: 'readonly',
      },
    },
    plugins: {
      react,
      'react-hooks': reactHooks,
    },
    rules: {
      'react/react-in-jsx-scope': 'off',
      'react/prop-types': 'off',
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
      'no-unused-vars': 'off', // Disable for JSX files - React plugin handles component usage
      'no-empty': ['warn', { allowEmptyCatch: true }],
    },
    settings: {
      react: {
        version: 'detect',
      },
    },
  },
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      parser: require('@typescript-eslint/parser'),
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        // Browser globals
        window: 'readonly',
        document: 'readonly',
        localStorage: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        // DOM types
        HTMLDivElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLButtonElement: 'readonly',
        HTMLSelectElement: 'readonly',
        HTMLImageElement: 'readonly',
        HTMLElement: 'readonly',
        Element: 'readonly',
        MouseEvent: 'readonly',
        KeyboardEvent: 'readonly',
        WheelEvent: 'readonly',
        Node: 'readonly',
        performance: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        queueMicrotask: 'readonly',
        alert: 'readonly',
        URL: 'readonly',
        ResizeObserver: 'readonly',
        Blob: 'readonly',
        AbortController: 'readonly',
        React: 'readonly',
        IntersectionObserver: 'readonly',
        FrameRequestCallback: 'readonly',
        // Bridge/API types (preload; used in renderer and in .d.ts)
        ApiKeyResult: 'readonly',
        BulkDeleteJobsResult: 'readonly',
        BulkExportJobsResult: 'readonly',
        BulkRerunJobsResult: 'readonly',
        DeleteJobResult: 'readonly',
        ExportJobResult: 'readonly',
        FileDialogOptions: 'readonly',
        FileSelectResult: 'readonly',
        FilteredJobsResult: 'readonly',
        GeneratedImage: 'readonly',
        JobConfiguration: 'readonly',
        JobError: 'readonly',
        JobExecution: 'readonly',
        JobFilters: 'readonly',
        JobHistoryResult: 'readonly',
        JobResultsResult: 'readonly',
        JobStatistics: 'readonly',
        JobStatus: 'readonly',
        LogEntry: 'readonly',
        ProgressUpdate: 'readonly',
        RenameJobResult: 'readonly',
        SecurityStatus: 'readonly',
        SettingsObject: 'readonly',
        SettingsResult: 'readonly',
        // Node.js globals
        NodeJS: 'readonly',
        process: 'readonly',
        require: 'readonly',
        module: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        global: 'readonly',
        Buffer: 'readonly',
        FormData: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': require('@typescript-eslint/eslint-plugin'),
      react,
      'react-hooks': reactHooks,
    },
    rules: {
      'react/react-in-jsx-scope': 'off',
      'react/prop-types': 'off',
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': 'warn',
      '@typescript-eslint/no-explicit-any': 'warn',
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'no-case-declarations': 'warn',
      'no-extra-boolean-cast': 'warn',
      'no-prototype-builtins': 'warn',
      'no-useless-catch': 'warn',
      'no-useless-escape': 'warn',
    },
    settings: {
      react: {
        version: 'detect',
      },
    },
  },
  {
    files: ['electron/**/*.js', 'src/**/*.js', 'scripts/**/*.js', 'website/**/*.js', '*.js', '*.ts'],
    languageOptions: {
      globals: {
        require: 'readonly',
        module: 'readonly',
        process: 'readonly',
        console: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        global: 'readonly',
        Buffer: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        setImmediate: 'readonly',
        clearImmediate: 'readonly',
        FormData: 'readonly',
        window: 'readonly',
        document: 'readonly',
        URL: 'readonly',
        queueMicrotask: 'readonly',
        NodeRequire: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'no-useless-catch': 'warn',
      'no-useless-escape': 'warn',
    },
  },
  // Renderer: bridge/API type names (preload exposes these)
  {
    files: ['src/renderer/**/*.{ts,tsx,js,jsx}'],
    languageOptions: {
      globals: {
        ApiKeyResult: 'readonly',
        BulkDeleteJobsResult: 'readonly',
        BulkExportJobsResult: 'readonly',
        BulkRerunJobsResult: 'readonly',
        DeleteJobResult: 'readonly',
        ExportJobResult: 'readonly',
        FileDialogOptions: 'readonly',
        FileSelectResult: 'readonly',
        FilteredJobsResult: 'readonly',
        GeneratedImage: 'readonly',
        JobConfiguration: 'readonly',
        JobError: 'readonly',
        JobExecution: 'readonly',
        JobFilters: 'readonly',
        JobHistoryResult: 'readonly',
        JobResultsResult: 'readonly',
        JobStatistics: 'readonly',
        JobStatus: 'readonly',
        LogEntry: 'readonly',
        ProgressUpdate: 'readonly',
        RenameJobResult: 'readonly',
        SecurityStatus: 'readonly',
        SettingsObject: 'readonly',
        SettingsResult: 'readonly',
      },
    },
  },
  {
    files: ['src/services/jobRunner.js'],
    rules: {
      'no-unused-vars': 'warn',
      'no-empty': 'warn',
      'no-undef': 'warn'
    }
  },
  {
    files: ['website/src/**/*.{tsx,jsx}'],
    languageOptions: {
      globals: {
        React: 'readonly',
      },
    },
  },
  {
    files: ['**/*.test.{js,ts,tsx}', '**/*.spec.{js,ts,tsx}', '**/__tests__/**/*.{js,ts,tsx}', 'tests/**/*.{js,ts,tsx}'],
    languageOptions: {
      globals: {
        // Vitest globals
        describe: 'readonly',
        test: 'readonly',
        it: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        vi: 'readonly',
        waitFor: 'readonly',
        NodeRequire: 'readonly',
        // Node.js globals
        require: 'readonly',
        module: 'readonly',
        process: 'readonly',
        console: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        global: 'readonly',
        Buffer: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
      'no-empty': 'warn',
    },
  },
  // Legacy panels (frozen per ADR-010): avoid refactors; relax hooks and no-empty
  {
    files: ['**/*.legacy.{tsx,jsx}'],
    rules: {
      'react-hooks/rules-of-hooks': 'off',
      'react-hooks/exhaustive-deps': 'off',
      'no-empty': ['warn', { allowEmptyCatch: true }],
    },
  },
  {
    ignores: [
      'node_modules/**',
      'dist/**',
      'build/**',
      'coverage/**',
      'playwright-report/**',
      'website/build/**',
      'electron/renderer/assets/**',
      'electron/renderer/electron/**',
    ],
  },
]; 